allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@stripe/cli': true
  '@tailwindcss/oxide': false
  core-js: true
  esbuild: false
  prisma: true
  sharp: true
  unrs-resolver: false
  vue-demi: false
  workerd: true
