// ANCHOR: Brand names by transaction category
import type { TransactionCategoryValue } from './categories'

export const BRAND_CATEGORIES: Record<TransactionCategoryValue, readonly string[]> = {
  HOUSING: [
    'Airbnb',
    'Booking.com',
    'Vrbo',
    'Zillow',
    'Rightmove',
    'Zoopla',
    'OpenRent',
    'SpareRoom',
    'Foxtons',
    'Purplebricks',
    'Realtor.com',
    'Trulia',
    'Redfin',
    'Compass',
    'Keller Williams',
    'Coldwell Banker',
    'Century 21',
    'RE/MAX',
    'CBRE',
    'Savills',
    'JLL',
    'Knight Frank',
    'British Gas',
    'HomeServe',
    'ADT',
    'Vivint',
    'SimpliSafe',
    'Ring',
    'Nest'
  ],

  FOOD: [
    'Tesco',
    'Sainsbury\'s',
    'Asda',
    'Morrisons',
    'Aldi',
    'Lidl',
    'Waitrose',
    'Co-op',
    'Marks & Spencer',
    'Ocado',
    'Whole Foods',
    'Walmart',
    'Costco',
    'Target',
    'Amazon Fresh',
    'Deliveroo',
    'Uber Eats',
    'Just Eat',
    'DoorDash',
    'Grubhub',
    'Instacart',
    'HelloFresh',
    'Gousto',
    'Mindful Chef',
    'Blue Apron',
    'Pret A Manger',
    'Starbucks',
    'Costa Coffee',
    'Greggs',
    'McDonald\'s',
    'Burger King',
    'KFC',
    'Subway',
    'Domino\'s',
    'Pizza Hut',
    'Papa John\'s',
    'Nando\'s',
    'Chipotle',
    'Five Guys'
  ],

  TRANSPORT: [
    'Uber',
    'Lyft',
    'Bolt',
    'FreeNow',
    'Ola',
    'Grab',
    'Gett',
    'Cabify',
    'Trainline',
    'National Rail',
    'TfL',
    'Amtrak',
    'Eurostar',
    'Avanti West Coast',
    'LNER',
    'Southern',
    'Great Western Railway',
    'Stagecoach',
    'Arriva',
    'First Bus',
    'National Express',
    'Megabus',
    'FlixBus',
    'Shell',
    'BP',
    'Esso',
    'Texaco',
    'Chevron',
    'Exxon',
    'TotalEnergies',
    'Circle K',
    'Waze',
    'Zipcar',
    'Turo',
    'Hertz',
    'Avis',
    'Enterprise',
    'Budget',
    'Sixt'
  ],

  SUBSCRIPTIONS: [
    'Netflix',
    'Disney+',
    'Disney Plus',
    'Amazon Prime',
    'Prime Video',
    'Amazon Music',
    'Spotify',
    'Apple Music',
    'YouTube Premium',
    'YouTube Music',
    'Hulu',
    'Max',
    'HBO Max',
    'Paramount+',
    'Peacock',
    'Crunchyroll',
    'BritBox',
    'NOW',
    'NOW TV',
    'Sky Go',
    'Sky Sports',
    'Sky Cinema',
    'Apple TV+',
    'Discovery+',
    'Viaplay',
    'MUBI',
    'Shudder',
    'CuriosityStream',
    'Hayu',
    'DAZN',
    'ESPN+',
    'NBA League Pass',
    'NFL Game Pass',
    'MLB TV',
    'F1 TV',
    'Tidal',
    'Deezer',
    'Audible',
    'Scribd',
    'Everand',
    'Kindle Unlimited',
    'Blinkist',
    'Headspace',
    'Calm',
    'Strava',
    'Peloton',
    'Fitbit Premium',
    'MyFitnessPal',
    'Adobe Creative Cloud',
    'Adobe Acrobat',
    'Canva Pro',
    'Figma Professional',
    'Notion Plus',
    'Notion AI',
    'ChatGPT Plus',
    'Claude Pro',
    'Perplexity Pro',
    'GitHub Copilot',
    'GitHub Pro',
    '1Password',
    'Bitwarden Premium',
    'Dashlane',
    'LastPass',
    'Dropbox Plus',
    'Dropbox Professional',
    'Google One',
    'iCloud+',
    'Microsoft 365',
    'Office 365',
    'OneDrive',
    'Box',
    'Proton Unlimited',
    'Proton Mail',
    'Proton Drive',
    'ExpressVPN',
    'NordVPN',
    'Surfshark',
    'PIA',
    'Private Internet Access',
    'CyberGhost',
    'Mullvad',
    'Proton VPN',
    'Keeper',
    'Todoist Pro',
    'TickTick Premium',
    'Grammarly',
    'Otter.ai',
    'Readwise',
    'Superhuman',
    'Linear',
    'Raycast Pro',
    'Arc Max',
    'Replit Core',
    'Lovable',
    'Cursor Pro',
    'Codeium Pro',
    'Windsurf Pro',
    'Midjourney',
    'Runway',
    'ElevenLabs',
    'Synthesia',
    'Descript',
    'CapCut Pro',
    'InVideo',
    'Envato Elements',
    'Storyblocks',
    'Shutterstock',
    'Epidemic Sound',
    'Artlist',
    'TradingView',
    'YNAB',
    'Monarch Money',
    'Copilot Money',
    'Rocket Money',
    'Truebill',
    'X Premium',
    'LinkedIn Premium',
    'Telegram Premium',
    'Discord Nitro',
    'Snapchat+',
    'Reddit Premium',
    'Medium',
    'Substack',
    'Patreon',
    'OnlyFans',
    'Beeper',
    'Zoom Pro',
    'Slack Pro',
    'Calendly',
    'Loom',
    'Miro',
    'ClickUp',
    'Asana',
    'Monday.com',
    'Trello Premium',
    'Airtable',
    'Coda',
    'Linear'
  ],

  UTILITIES: [
    'British Gas',
    'EDF',
    'E.ON',
    'Octopus Energy',
    'OVO Energy',
    'Scottish Power',
    'SSE',
    'Thames Water',
    'Anglian Water',
    'Severn Trent',
    'United Utilities',
    'Virgin Media',
    'BT',
    'Sky',
    'TalkTalk',
    'EE',
    'Vodafone',
    'O2',
    'Three',
    'Plusnet',
    'Hyperoptic',
    'Community Fibre',
    'Google Fi',
    'AT&T',
    'Verizon',
    'T-Mobile',
    'Xfinity',
    'Spectrum'
  ],

  HEALTHCARE: [
    'Boots',
    'Lloyds Pharmacy',
    'CVS',
    'Walgreens',
    'Rite Aid',
    'Nuffield Health',
    'Bupa',
    'Vitality',
    'AXA Health',
    'Simplyhealth',
    'Hims',
    'Hers',
    'Zocdoc',
    'Teladoc',
    'BetterHelp'
  ],

  ENTERTAINMENT: [
    'Steam',
    'PlayStation',
    'PlayStation Plus',
    'Xbox',
    'Xbox Game Pass',
    'Nintendo',
    'Epic Games',
    'EA Play',
    'Ubisoft+',
    'Battle.net',
    'Twitch',
    'Netflix',
    'Spotify',
    'Disney+',
    'Apple TV+',
    'Vue',
    'Odeon',
    'Cineworld',
    'AMC',
    'Regal'
  ],

  EDUCATION: [
    'Coursera',
    'Udemy',
    'edX',
    'Skillshare',
    'MasterClass',
    'Pluralsight',
    'LinkedIn Learning',
    'DataCamp',
    'Brilliant',
    'Duolingo',
    'Babbel',
    'Rosetta Stone',
    'Codecademy',
    'Treehouse',
    'Frontend Masters',
    'Egghead',
    'Educative',
    'Scrimba',
    'Khan Academy',
    'FutureLearn'
  ],

  SHOPPING: [
    'Amazon',
    'eBay',
    'Etsy',
    'AliExpress',
    'Temu',
    'Shein',
    'ASOS',
    'Zalando',
    'Nike',
    'Adidas',
    'Apple',
    'Samsung',
    'Currys',
    'Argos',
    'John Lewis',
    'Next',
    'Marks & Spencer',
    'IKEA',
    'Wayfair',
    'Costco'
  ],

  SAVINGS: [
    'Vanguard',
    'Fidelity',
    'Charles Schwab',
    'Robinhood',
    'Wealthfront',
    'Betterment',
    'Nutmeg',
    'Moneybox',
    'Plum',
    'Acorns',
    'Trading 212',
    'Interactive Brokers',
    'Hargreaves Lansdown'
  ],

  INCOME: [
    'PayPal',
    'Stripe',
    'Wise',
    'Payoneer',
    'Square',
    'Shopify',
    'Upwork',
    'Fiverr',
    'Freelancer',
    'Toptal',
    'Deel',
    'Remote',
    'Gusto',
    'Rippling',
    'Patreon',
    'Substack',
    'OnlyFans',
    'Etsy',
    'eBay',
    'Amazon'
  ],

  CLOUD_INFRA: [
    'Amazon Web Services',
    'AWS',
    'Microsoft Azure',
    'Google Cloud',
    'Cloudflare',
    'DigitalOcean',
    'Linode',
    'Vultr',
    'Render',
    'Railway',
    'Fly.io',
    'Vercel',
    'Netlify',
    'Firebase',
    'Supabase',
    'PlanetScale',
    'Neon',
    'MongoDB Atlas',
    'Heroku',
    'Oracle Cloud',
    'IBM Cloud',
    'Akamai',
    'Fastly',
    'Bunny.net',
    'Hetzner',
    'OVHcloud',
    'Scaleway'
  ],

  DEVELOPER_TOOLS: [
    'GitHub',
    'GitLab',
    'Bitbucket',
    'GitHub Copilot',
    'Cursor',
    'Windsurf',
    'Codeium',
    'JetBrains',
    'Visual Studio',
    'Postman',
    'Insomnia',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Datadog',
    'New Relic',
    'Sentry',
    'Grafana',
    'Linear',
    'Jira',
    'Confluence',
    'Notion',
    'Slack',
    'Discord',
    'Vercel',
    'Netlify',
    'Replit',
    'Glitch',
    'CircleCI',
    'GitHub Actions',
    'Buildkite',
    'Semaphore',
    'Codecov',
    'SonarCloud',
    'LaunchDarkly',
    'PagerDuty',
    'Statuspage',
    'Auth0',
    'Clerk',
    'Okta',
    'Stripe',
    'Twilio',
    'SendGrid',
    'Resend',
    'Algolia',
    'OpenAI',
    'Anthropic',
    'Cohere',
    'Pinecone',
    'Weaviate',
    'Redis Cloud'
  ],

  OTHER: []
}
